# This file is used for registering your Utopia models project with the Utopia
# frontend (utopya). It contains information about your projects structure and
# some optional metadata.
#
# NOTE The Cmake build system registers your project according to the content
#      of this file each time you let Cmake run.
#      If you change this file, make sure to run `cmake ..` afterwards.
---
# The name under which the models inside this project can be grouped.
# The project name needs to be exactly the same as the CMAKE_PROJECT_NAME
project_name: UtopiaModelsMulan

# The name of the framework this project uses: Utopia
framework_name: Utopia

paths:
  models_dir: src/models

  # Python models tests and model plots directories
  py_tests_dir: python/model_tests
  py_plots_dir: python/model_plots

  # Project-level multiverse configuration and base plots file
  mv_project_cfg: python/multiverse_cfg.yml
  project_base_plots: python/base_plots.yml

metadata:
  long_name: MuLAN
  description: Multilayered Adaptive Network Model of evolutionary processes
  # long_description: This project ...
  language: c++
  # license: LGPLv3+
  authors:
    - Simeon Scheib

run_cfg_format: yaml
